/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.MyJavaGrammarAccess;

public class MyJavaParser extends AbstractContentAssistParser {
	
	@Inject
	private MyJavaGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyJavaParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyJavaParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyJavaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getType_declarationAccess().getAlternatives_1(), "rule__Type_declaration__Alternatives_1");
					put(grammarAccess.getField_declarationAccess().getAlternatives(), "rule__Field_declaration__Alternatives");
					put(grammarAccess.getField_declarationAccess().getAlternatives_0_1(), "rule__Field_declaration__Alternatives_0_1");
					put(grammarAccess.getMethod_declarationAccess().getAlternatives_7(), "rule__Method_declaration__Alternatives_7");
					put(grammarAccess.getType_specifierAccess().getAlternatives(), "rule__Type_specifier__Alternatives");
					put(grammarAccess.getModifierAccess().getAlternatives(), "rule__Modifier__Alternatives");
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
					put(grammarAccess.getNumeric_Expression_lineAccess().getAlternatives(), "rule__Numeric_Expression_line__Alternatives");
					put(grammarAccess.getUNARYOPAccess().getAlternatives(), "rule__UNARYOP__Alternatives");
					put(grammarAccess.getINCREMENTAccess().getAlternatives(), "rule__INCREMENT__Alternatives");
					put(grammarAccess.getOPAccess().getAlternatives(), "rule__OP__Alternatives");
					put(grammarAccess.getExpression_lineAccess().getAlternatives(), "rule__Expression_line__Alternatives");
					put(grammarAccess.getSwitch_statementAccess().getAlternatives_5(), "rule__Switch_statement__Alternatives_5");
					put(grammarAccess.getFor_StatementAccess().getAlternatives_1(), "rule__For_Statement__Alternatives_1");
					put(grammarAccess.getImport_statementAccess().getAlternatives_1(), "rule__Import_statement__Alternatives_1");
					put(grammarAccess.getCompilation_unitAccess().getGroup(), "rule__Compilation_unit__Group__0");
					put(grammarAccess.getType_declarationAccess().getGroup(), "rule__Type_declaration__Group__0");
					put(grammarAccess.getInterface_declarationAccess().getGroup(), "rule__Interface_declaration__Group__0");
					put(grammarAccess.getInterface_declarationAccess().getGroup_3(), "rule__Interface_declaration__Group_3__0");
					put(grammarAccess.getInterface_declarationAccess().getGroup_3_2(), "rule__Interface_declaration__Group_3_2__0");
					put(grammarAccess.getClass_declarationAccess().getGroup(), "rule__Class_declaration__Group__0");
					put(grammarAccess.getClass_declarationAccess().getGroup_3(), "rule__Class_declaration__Group_3__0");
					put(grammarAccess.getClass_declarationAccess().getGroup_4(), "rule__Class_declaration__Group_4__0");
					put(grammarAccess.getClass_declarationAccess().getGroup_4_2(), "rule__Class_declaration__Group_4_2__0");
					put(grammarAccess.getField_declarationAccess().getGroup_0(), "rule__Field_declaration__Group_0__0");
					put(grammarAccess.getMethod_declarationAccess().getGroup(), "rule__Method_declaration__Group__0");
					put(grammarAccess.getMethod_declarationAccess().getGroup_6(), "rule__Method_declaration__Group_6__0");
					put(grammarAccess.getConstructor_declarationAccess().getGroup(), "rule__Constructor_declaration__Group__0");
					put(grammarAccess.getParameter_listAccess().getGroup(), "rule__Parameter_list__Group__0");
					put(grammarAccess.getParameter_listAccess().getGroup_1(), "rule__Parameter_list__Group_1__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getParameterAccess().getGroup_2(), "rule__Parameter__Group_2__0");
					put(grammarAccess.getVariable_declarationAccess().getGroup(), "rule__Variable_declaration__Group__0");
					put(grammarAccess.getVariable_declarationAccess().getGroup_3(), "rule__Variable_declaration__Group_3__0");
					put(grammarAccess.getVariable_declaratorAccess().getGroup(), "rule__Variable_declarator__Group__0");
					put(grammarAccess.getVariable_declaratorAccess().getGroup_1(), "rule__Variable_declarator__Group_1__0");
					put(grammarAccess.getTypeAccess().getGroup(), "rule__Type__Group__0");
					put(grammarAccess.getTypeAccess().getGroup_1(), "rule__Type__Group_1__0");
					put(grammarAccess.getStatic_initializerAccess().getGroup(), "rule__Static_initializer__Group__0");
					put(grammarAccess.getStatement_blockAccess().getGroup(), "rule__Statement_block__Group__0");
					put(grammarAccess.getStatementAccess().getGroup_1(), "rule__Statement__Group_1__0");
					put(grammarAccess.getStatementAccess().getGroup_7(), "rule__Statement__Group_7__0");
					put(grammarAccess.getStatementAccess().getGroup_8(), "rule__Statement__Group_8__0");
					put(grammarAccess.getStatementAccess().getGroup_9(), "rule__Statement__Group_9__0");
					put(grammarAccess.getStatementAccess().getGroup_12(), "rule__Statement__Group_12__0");
					put(grammarAccess.getStatementAccess().getGroup_13(), "rule__Statement__Group_13__0");
					put(grammarAccess.getStatementAccess().getGroup_14(), "rule__Statement__Group_14__0");
					put(grammarAccess.getStatementAccess().getGroup_15(), "rule__Statement__Group_15__0");
					put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
					put(grammarAccess.getExpressionAccess().getGroup_2(), "rule__Expression__Group_2__0");
					put(grammarAccess.getExpressionAccess().getGroup_3(), "rule__Expression__Group_3__0");
					put(grammarAccess.getExpressionAccess().getGroup_4(), "rule__Expression__Group_4__0");
					put(grammarAccess.getExpressionAccess().getGroup_5(), "rule__Expression__Group_5__0");
					put(grammarAccess.getExpressionAccess().getGroup_6(), "rule__Expression__Group_6__0");
					put(grammarAccess.getExpressionAccess().getGroup_7(), "rule__Expression__Group_7__0");
					put(grammarAccess.getExpressionAccess().getGroup_8(), "rule__Expression__Group_8__0");
					put(grammarAccess.getNumeric_ExpressionAccess().getGroup(), "rule__Numeric_Expression__Group__0");
					put(grammarAccess.getNumeric_Expression_lineAccess().getGroup_0(), "rule__Numeric_Expression_line__Group_0__0");
					put(grammarAccess.getNumeric_Expression_lineAccess().getGroup_1(), "rule__Numeric_Expression_line__Group_1__0");
					put(grammarAccess.getExpression_lineAccess().getGroup_0(), "rule__Expression_line__Group_0__0");
					put(grammarAccess.getArglistAccess().getGroup(), "rule__Arglist__Group__0");
					put(grammarAccess.getArglistAccess().getGroup_1(), "rule__Arglist__Group_1__0");
					put(grammarAccess.getSwitch_statementAccess().getGroup(), "rule__Switch_statement__Group__0");
					put(grammarAccess.getSwitch_statementAccess().getGroup_5_0(), "rule__Switch_statement__Group_5_0__0");
					put(grammarAccess.getFor_StatementAccess().getGroup(), "rule__For_Statement__Group__0");
					put(grammarAccess.getWhile_StatementAccess().getGroup(), "rule__While_Statement__Group__0");
					put(grammarAccess.getDo_StatementAccess().getGroup(), "rule__Do_Statement__Group__0");
					put(grammarAccess.getIf_statementAccess().getGroup(), "rule__If_statement__Group__0");
					put(grammarAccess.getIf_statementAccess().getGroup_3(), "rule__If_statement__Group_3__0");
					put(grammarAccess.getTry_statementAccess().getGroup(), "rule__Try_statement__Group__0");
					put(grammarAccess.getTry_statementAccess().getGroup_2(), "rule__Try_statement__Group_2__0");
					put(grammarAccess.getTry_statementAccess().getGroup_3(), "rule__Try_statement__Group_3__0");
					put(grammarAccess.getImport_statementAccess().getGroup(), "rule__Import_statement__Group__0");
					put(grammarAccess.getImport_statementAccess().getGroup_1_0(), "rule__Import_statement__Group_1_0__0");
					put(grammarAccess.getImport_statementAccess().getGroup_1_1(), "rule__Import_statement__Group_1_1__0");
					put(grammarAccess.getPackage_statementAccess().getGroup(), "rule__Package_statement__Group__0");
					put(grammarAccess.getPackage_nameAccess().getGroup(), "rule__Package_name__Group__0");
					put(grammarAccess.getPackage_name_lineAccess().getGroup(), "rule__Package_name_line__Group__0");
					put(grammarAccess.getModelAccess().getGreetingsAssignment(), "rule__Model__GreetingsAssignment");
					put(grammarAccess.getCompilation_unitAccess().getNameAssignment_0(), "rule__Compilation_unit__NameAssignment_0");
					put(grammarAccess.getCompilation_unitAccess().getImportsAssignment_1(), "rule__Compilation_unit__ImportsAssignment_1");
					put(grammarAccess.getCompilation_unitAccess().getTypeDeclarationsAssignment_2(), "rule__Compilation_unit__TypeDeclarationsAssignment_2");
					put(grammarAccess.getType_declarationAccess().getCommentAssignment_0(), "rule__Type_declaration__CommentAssignment_0");
					put(grammarAccess.getType_declarationAccess().getClassDecAssignment_1_0(), "rule__Type_declaration__ClassDecAssignment_1_0");
					put(grammarAccess.getType_declarationAccess().getInterfaceDecAssignment_1_1(), "rule__Type_declaration__InterfaceDecAssignment_1_1");
					put(grammarAccess.getInterface_declarationAccess().getModifiersAssignment_0(), "rule__Interface_declaration__ModifiersAssignment_0");
					put(grammarAccess.getInterface_declarationAccess().getInterfaceNameAssignment_2(), "rule__Interface_declaration__InterfaceNameAssignment_2");
					put(grammarAccess.getInterface_declarationAccess().getInterfaceHerdadaAssignment_3_1(), "rule__Interface_declaration__InterfaceHerdadaAssignment_3_1");
					put(grammarAccess.getInterface_declarationAccess().getInterfacesHerdadasAssignment_3_2_1(), "rule__Interface_declaration__InterfacesHerdadasAssignment_3_2_1");
					put(grammarAccess.getClass_declarationAccess().getModifiersAssignment_0(), "rule__Class_declaration__ModifiersAssignment_0");
					put(grammarAccess.getClass_declarationAccess().getClassNameAssignment_2(), "rule__Class_declaration__ClassNameAssignment_2");
					put(grammarAccess.getClass_declarationAccess().getClassHerdadaAssignment_3_1(), "rule__Class_declaration__ClassHerdadaAssignment_3_1");
					put(grammarAccess.getClass_declarationAccess().getInterfaceImplementadaAssignment_4_1(), "rule__Class_declaration__InterfaceImplementadaAssignment_4_1");
					put(grammarAccess.getClass_declarationAccess().getInterfacesImplementadasAssignment_4_2_1(), "rule__Class_declaration__InterfacesImplementadasAssignment_4_2_1");
					put(grammarAccess.getClass_declarationAccess().getFieldsDeclarationAssignment_6(), "rule__Class_declaration__FieldsDeclarationAssignment_6");
					put(grammarAccess.getField_declarationAccess().getCommentAssignment_0_0(), "rule__Field_declaration__CommentAssignment_0_0");
					put(grammarAccess.getField_declarationAccess().getVariableDeclarationAssignment_0_1_0(), "rule__Field_declaration__VariableDeclarationAssignment_0_1_0");
					put(grammarAccess.getField_declarationAccess().getContructorNameAssignment_0_1_1(), "rule__Field_declaration__ContructorNameAssignment_0_1_1");
					put(grammarAccess.getField_declarationAccess().getMethodNameAssignment_0_1_2(), "rule__Field_declaration__MethodNameAssignment_0_1_2");
					put(grammarAccess.getField_declarationAccess().getStaticinitializerAssignment_1(), "rule__Field_declaration__StaticinitializerAssignment_1");
					put(grammarAccess.getMethod_declarationAccess().getModifiersMethodAssignment_0(), "rule__Method_declaration__ModifiersMethodAssignment_0");
					put(grammarAccess.getMethod_declarationAccess().getTypeMethodAssignment_1(), "rule__Method_declaration__TypeMethodAssignment_1");
					put(grammarAccess.getMethod_declarationAccess().getNameMethodAssignment_2(), "rule__Method_declaration__NameMethodAssignment_2");
					put(grammarAccess.getMethod_declarationAccess().getLParenAssignment_3(), "rule__Method_declaration__LParenAssignment_3");
					put(grammarAccess.getMethod_declarationAccess().getParameterListMethodAssignment_4(), "rule__Method_declaration__ParameterListMethodAssignment_4");
					put(grammarAccess.getMethod_declarationAccess().getRparentAssignment_5(), "rule__Method_declaration__RparentAssignment_5");
					put(grammarAccess.getMethod_declarationAccess().getStatementMethodAssignment_7_0(), "rule__Method_declaration__StatementMethodAssignment_7_0");
					put(grammarAccess.getMethod_declarationAccess().getDebugAssignment_7_1(), "rule__Method_declaration__DebugAssignment_7_1");
					put(grammarAccess.getConstructor_declarationAccess().getModifiersConstructorAssignment_0(), "rule__Constructor_declaration__ModifiersConstructorAssignment_0");
					put(grammarAccess.getConstructor_declarationAccess().getNameConstructorAssignment_1(), "rule__Constructor_declaration__NameConstructorAssignment_1");
					put(grammarAccess.getConstructor_declarationAccess().getLParenAssignment_2(), "rule__Constructor_declaration__LParenAssignment_2");
					put(grammarAccess.getConstructor_declarationAccess().getParameterListConstructorAssignment_3(), "rule__Constructor_declaration__ParameterListConstructorAssignment_3");
					put(grammarAccess.getConstructor_declarationAccess().getRparentAssignment_4(), "rule__Constructor_declaration__RparentAssignment_4");
					put(grammarAccess.getConstructor_declarationAccess().getStatementConstructorAssignment_5(), "rule__Constructor_declaration__StatementConstructorAssignment_5");
					put(grammarAccess.getParameter_listAccess().getParameterAssignment_0(), "rule__Parameter_list__ParameterAssignment_0");
					put(grammarAccess.getParameter_listAccess().getParametersAssignment_1_1(), "rule__Parameter_list__ParametersAssignment_1_1");
					put(grammarAccess.getParameterAccess().getTypeAssignment_0(), "rule__Parameter__TypeAssignment_0");
					put(grammarAccess.getParameterAccess().getParameterNameAssignment_1(), "rule__Parameter__ParameterNameAssignment_1");
					put(grammarAccess.getVariable_declarationAccess().getModifiersVariableAssignment_0(), "rule__Variable_declaration__ModifiersVariableAssignment_0");
					put(grammarAccess.getVariable_declarationAccess().getTypeAssignment_1(), "rule__Variable_declaration__TypeAssignment_1");
					put(grammarAccess.getVariable_declarationAccess().getNameVariableAssignment_2(), "rule__Variable_declaration__NameVariableAssignment_2");
					put(grammarAccess.getVariable_declarationAccess().getNamesAssignment_3_1(), "rule__Variable_declaration__NamesAssignment_3_1");
					put(grammarAccess.getVariable_declaratorAccess().getNameVariableAssignment_0(), "rule__Variable_declarator__NameVariableAssignment_0");
					put(grammarAccess.getTypeAccess().getTypeSpecifierAssignment_0(), "rule__Type__TypeSpecifierAssignment_0");
					put(grammarAccess.getStatic_initializerAccess().getStaticAssignment_0(), "rule__Static_initializer__StaticAssignment_0");
					put(grammarAccess.getStatic_initializerAccess().getNameAssignment_1(), "rule__Static_initializer__NameAssignment_1");
					put(grammarAccess.getStatement_blockAccess().getStatmentsAssignment_2(), "rule__Statement_block__StatmentsAssignment_2");
					put(grammarAccess.getStatementAccess().getVariableDeclarationAssignment_0(), "rule__Statement__VariableDeclarationAssignment_0");
					put(grammarAccess.getStatementAccess().getExpressionStatementAssignment_1_0(), "rule__Statement__ExpressionStatementAssignment_1_0");
					put(grammarAccess.getStatementAccess().getGAssignment_1_1(), "rule__Statement__GAssignment_1_1");
					put(grammarAccess.getStatementAccess().getIfStatementAssignment_2(), "rule__Statement__IfStatementAssignment_2");
					put(grammarAccess.getStatementAccess().getDoStatementAssignment_3(), "rule__Statement__DoStatementAssignment_3");
					put(grammarAccess.getStatementAccess().getWhileStatementAssignment_4(), "rule__Statement__WhileStatementAssignment_4");
					put(grammarAccess.getStatementAccess().getForStatementAssignment_5(), "rule__Statement__ForStatementAssignment_5");
					put(grammarAccess.getStatementAccess().getSwitchStatementAssignment_6(), "rule__Statement__SwitchStatementAssignment_6");
					put(grammarAccess.getStatementAccess().getRparentAssignment_7_1(), "rule__Statement__RparentAssignment_7_1");
					put(grammarAccess.getStatementAccess().getSyncStatementAssignment_7_2(), "rule__Statement__SyncStatementAssignment_7_2");
					put(grammarAccess.getStatementAccess().getTryStatementAssignment_11(), "rule__Statement__TryStatementAssignment_11");
					put(grammarAccess.getStatementAccess().getNameStatementAssignment_12_0(), "rule__Statement__NameStatementAssignment_12_0");
					put(grammarAccess.getStatementAccess().getStatementAssignment_12_2(), "rule__Statement__StatementAssignment_12_2");
					put(grammarAccess.getStatementAccess().getNameAssignment_13_2(), "rule__Statement__NameAssignment_13_2");
					put(grammarAccess.getStatementAccess().getNameAssignment_14_2(), "rule__Statement__NameAssignment_14_2");
					put(grammarAccess.getExpressionAccess().getExpressionAssignment_0(), "rule__Expression__ExpressionAssignment_0");
					put(grammarAccess.getExpressionAccess().getLParenAssignment_1_0(), "rule__Expression__LParenAssignment_1_0");
					put(grammarAccess.getExpressionAccess().getExpressionAssignment_1_1(), "rule__Expression__ExpressionAssignment_1_1");
					put(grammarAccess.getExpressionAccess().getRparentAssignment_1_2(), "rule__Expression__RparentAssignment_1_2");
					put(grammarAccess.getExpressionAccess().getExpressionLineAssignment_1_3(), "rule__Expression__ExpressionLineAssignment_1_3");
					put(grammarAccess.getExpressionAccess().getExpressionAssignment_2_1(), "rule__Expression__ExpressionAssignment_2_1");
					put(grammarAccess.getExpressionAccess().getExpressionLineAssignment_2_3(), "rule__Expression__ExpressionLineAssignment_2_3");
					put(grammarAccess.getExpressionAccess().getExpressionAssignment_3_1(), "rule__Expression__ExpressionAssignment_3_1");
					put(grammarAccess.getExpressionAccess().getExpressionLineAssignment_3_2(), "rule__Expression__ExpressionLineAssignment_3_2");
					put(grammarAccess.getExpressionAccess().getExpressionAssignment_4_1(), "rule__Expression__ExpressionAssignment_4_1");
					put(grammarAccess.getExpressionAccess().getExpressionLineAssignment_4_2(), "rule__Expression__ExpressionLineAssignment_4_2");
					put(grammarAccess.getExpressionAccess().getNameAssignment_5_0(), "rule__Expression__NameAssignment_5_0");
					put(grammarAccess.getExpressionAccess().getExpressionAssignment_5_1(), "rule__Expression__ExpressionAssignment_5_1");
					put(grammarAccess.getExpressionAccess().getExpressionAssignment_6_1(), "rule__Expression__ExpressionAssignment_6_1");
					put(grammarAccess.getExpressionAccess().getExpressionAssignment_7_1(), "rule__Expression__ExpressionAssignment_7_1");
					put(grammarAccess.getExpressionAccess().getExpressionAssignment_8_1(), "rule__Expression__ExpressionAssignment_8_1");
					put(grammarAccess.getNumeric_ExpressionAccess().getUnaryOpAssignment_0(), "rule__Numeric_Expression__UnaryOpAssignment_0");
					put(grammarAccess.getNumeric_ExpressionAccess().getExpressionAssignment_1(), "rule__Numeric_Expression__ExpressionAssignment_1");
					put(grammarAccess.getNumeric_ExpressionAccess().getNumericExpressionLineAssignment_2(), "rule__Numeric_Expression__NumericExpressionLineAssignment_2");
					put(grammarAccess.getNumeric_Expression_lineAccess().getIncrementAssignment_0_0(), "rule__Numeric_Expression_line__IncrementAssignment_0_0");
					put(grammarAccess.getNumeric_Expression_lineAccess().getExpressionLineAssignment_0_1(), "rule__Numeric_Expression_line__ExpressionLineAssignment_0_1");
					put(grammarAccess.getNumeric_Expression_lineAccess().getOpAssignment_1_0(), "rule__Numeric_Expression_line__OpAssignment_1_0");
					put(grammarAccess.getNumeric_Expression_lineAccess().getExpressionAssignment_1_1(), "rule__Numeric_Expression_line__ExpressionAssignment_1_1");
					put(grammarAccess.getNumeric_Expression_lineAccess().getExpressionLineAssignment_1_2(), "rule__Numeric_Expression_line__ExpressionLineAssignment_1_2");
					put(grammarAccess.getExpression_lineAccess().getLParenAssignment_0_0(), "rule__Expression_line__LParenAssignment_0_0");
					put(grammarAccess.getExpression_lineAccess().getRparentAssignment_0_1(), "rule__Expression_line__RparentAssignment_0_1");
					put(grammarAccess.getExpression_lineAccess().getExpressionAssignment_0_2(), "rule__Expression_line__ExpressionAssignment_0_2");
					put(grammarAccess.getArglistAccess().getExpressionAssignment_0(), "rule__Arglist__ExpressionAssignment_0");
					put(grammarAccess.getArglistAccess().getExpressionsAssignment_1_1(), "rule__Arglist__ExpressionsAssignment_1_1");
					put(grammarAccess.getSwitch_statementAccess().getLParenAssignment_2(), "rule__Switch_statement__LParenAssignment_2");
					put(grammarAccess.getSwitch_statementAccess().getRparentAssignment_3(), "rule__Switch_statement__RparentAssignment_3");
					put(grammarAccess.getSwitch_statementAccess().getSwitchStatementsAssignment_5_2(), "rule__Switch_statement__SwitchStatementsAssignment_5_2");
					put(grammarAccess.getFor_StatementAccess().getVariableAssignment_1_0(), "rule__For_Statement__VariableAssignment_1_0");
					put(grammarAccess.getFor_StatementAccess().getRParentAssignment_4(), "rule__For_Statement__RParentAssignment_4");
					put(grammarAccess.getFor_StatementAccess().getForStatementAssignment_5(), "rule__For_Statement__ForStatementAssignment_5");
					put(grammarAccess.getWhile_StatementAccess().getRparentAssignment_1(), "rule__While_Statement__RparentAssignment_1");
					put(grammarAccess.getWhile_StatementAccess().getWhileStatementAssignment_2(), "rule__While_Statement__WhileStatementAssignment_2");
					put(grammarAccess.getDo_StatementAccess().getDoStatementAssignment_1(), "rule__Do_Statement__DoStatementAssignment_1");
					put(grammarAccess.getDo_StatementAccess().getRparentAssignment_3(), "rule__Do_Statement__RparentAssignment_3");
					put(grammarAccess.getIf_statementAccess().getRparentAssignment_1(), "rule__If_statement__RparentAssignment_1");
					put(grammarAccess.getIf_statementAccess().getIdStatementAssignment_2(), "rule__If_statement__IdStatementAssignment_2");
					put(grammarAccess.getIf_statementAccess().getElseStatementAssignment_3_1(), "rule__If_statement__ElseStatementAssignment_3_1");
					put(grammarAccess.getTry_statementAccess().getTryStatementAssignment_1(), "rule__Try_statement__TryStatementAssignment_1");
					put(grammarAccess.getTry_statementAccess().getLParenAssignment_2_1(), "rule__Try_statement__LParenAssignment_2_1");
					put(grammarAccess.getTry_statementAccess().getParametersAssignment_2_2(), "rule__Try_statement__ParametersAssignment_2_2");
					put(grammarAccess.getTry_statementAccess().getRparentAssignment_2_3(), "rule__Try_statement__RparentAssignment_2_3");
					put(grammarAccess.getTry_statementAccess().getCatchStatementAssignment_2_4(), "rule__Try_statement__CatchStatementAssignment_2_4");
					put(grammarAccess.getTry_statementAccess().getFinallyStatementAssignment_3_1(), "rule__Try_statement__FinallyStatementAssignment_3_1");
					put(grammarAccess.getImport_statementAccess().getClassNameAssignment_1_0_0(), "rule__Import_statement__ClassNameAssignment_1_0_0");
					put(grammarAccess.getImport_statementAccess().getPacNameAssignment_1_1_0(), "rule__Import_statement__PacNameAssignment_1_1_0");
					put(grammarAccess.getPackage_statementAccess().getPacNameAssignment_1(), "rule__Package_statement__PacNameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyJavaParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyJavaParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyJavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyJavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
