/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.validation;

import org.xtext.example.mydsl.validation.AbstractMyJavaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyJavaValidator extends AbstractMyJavaValidator {
}
