/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.validation;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl.myDsl.Class_declaration;
import org.xtext.example.mydsl.myDsl.Field_declaration;
import org.xtext.example.mydsl.myDsl.Interface_declaration;
import org.xtext.example.mydsl.myDsl.Method_declaration;
import org.xtext.example.mydsl.myDsl.Type_declaration;
import org.xtext.example.mydsl.validation.AbstractMyDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyDslValidator extends AbstractMyDslValidator {
  public Map<String, List<String>> classeExtends = new HashMap<String, List<String>>();
  
  @Check
  public void validaTypeDeclaration(final Type_declaration td) {
    Class_declaration _classDec = td.getClassDec();
    if ((_classDec instanceof Class_declaration)) {
      Class_declaration _classDec_1 = td.getClassDec();
      Class_declaration cd = ((Class_declaration) _classDec_1);
      this.validaClass(cd);
    } else {
      Interface_declaration _interfaceDec = td.getInterfaceDec();
      Interface_declaration id = ((Interface_declaration) _interfaceDec);
      this.validaInterface(id);
    }
  }
  
  public void validaInterface(final Interface_declaration declaration) {
    EList<String> _modifiers = declaration.getModifiers();
    this.validaModifiers(_modifiers);
    EList<Field_declaration> _fieldsDeclaration = declaration.getFieldsDeclaration();
    for (final Field_declaration field : _fieldsDeclaration) {
      this.validaFieldDeclaration(field);
    }
  }
  
  public void validaFieldDeclaration(final Field_declaration declaration) {
    throw new UnsupportedOperationException("TODO: auto-generated method stub");
  }
  
  public void validaModifiers(final EList<String> list) {
    throw new UnsupportedOperationException("TODO: auto-generated method stub");
  }
  
  public void validaClass(final Class_declaration declaration) {
    EList<String> _modifiers = declaration.getModifiers();
    this.validaModifiers(_modifiers);
    EList<String> interfaces = declaration.getInterfacesImplementadas();
    String _interfaceImplementada = declaration.getInterfaceImplementada();
    interfaces.add(_interfaceImplementada);
    for (final String interfaceName : interfaces) {
      this.validaHerancaInterface(declaration, interfaceName);
    }
    String _classHerdada = declaration.getClassHerdada();
    this.validaHerancaClass(_classHerdada);
  }
  
  public void validaHerancaClass(final String string) {
    throw new UnsupportedOperationException("TODO: auto-generated method stub");
  }
  
  public void validaHerancaInterface(final Class_declaration declaration, final String string) {
    throw new UnsupportedOperationException("TODO: auto-generated method stub");
  }
  
  @Check
  public void checkMethodDeclaration(final Method_declaration md) {
    EList<String> methodMods = md.getModifiersMethod();
    int a = 0;
    for (final String mod : methodMods) {
      boolean _and = false;
      if (!(a == 0)) {
        _and = false;
      } else {
        boolean _equals = mod.equals("public");
        _and = _equals;
      }
      if (_and) {
      }
    }
  }
}
