/*
 * generated by Xtext
 */
package org.xtext.compilador.java;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends org.xtext.compilador.java.AbstractMyDslRuntimeModule {

}
